### PR TITLE
feat: add dynamic file load

### PR DESCRIPTION
**Pull request by erhise**
### UPDATE
Added script to load dynamic file

Usage:
```
npm run sandbox erik // <-- will run erik.ts if exists otherwise app.ts
npm run sandbox  // <-- defaults to app.ts
```

Simple cleanup of tsonfig.json. Think some configuration can be changed but I didnt see any need for it right now. I was also wondering about replacing tslint with eslint instead; but I also realize it will not bring that much value. Thoughts?

### CODE REVIEW

**Comment by erhise** [comment]
@siguse right now npm run vim will only support default app.ts run

**Review by siguse — APPROVED** [review]
Looking super sweet! 🍭

**Comment by siguse** [comment]
> ### UPDATE
> Added script to load dynamic file
> 
> Usage:
> ```
> npm run sandbox erik // <-- will run erik.ts if exists otherwise app.ts
> npm run sandbox  // <-- defaults to app.ts
> ```
> 
> Simple cleanup of tsonfig.json. Think some configuration can be changed but I didnt see any need for it right now. I was also wondering about replacing tslint with eslint instead; but I also realize it will not bring that much value. Thoughts? 

I guess it is desirable to use eslint since tslint is deprecated. But no hurry as far as I'm concerned :-)

**Comment by siguse** [comment]
> @siguse right now `npm run vim` will only support default app.ts run

Will look into it! :)

**Pull request merged**
